name: Rasa CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on push to the 'main' branch

jobs:
  Install_rasa:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install Rasa dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python3.8 -m venv venv
          source venv/bin/activate
          python3.8 -m pip install rasa --use-pep517

      # Step 4: Validate Rasa model
      - name: Validate Rasa files
        run: |
          source venv/bin/activate
          rasa data validate

      # Step 5: Run Rasa NLU tests
      - name: Run NLU tests
        run: |
          source venv/bin/activate
          rasa test nlu

      # Step 6: Run Core tests (stories)
      - name: Run Core tests
        run: |
          source venv/bin/activate
          rasa test core
  
  install_postgreSQL:
  runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
         - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL Service
        run: |
          sudo service postgresql start

      - name: Set up PostgreSQL Database and User
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ env.POSTGRES_PASSWORD }}';"
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.POSTGRES_DB }};"

      - name: Test Connection to PostgreSQL
        run: |
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c '\conninfo'

      - name: Run SQL Commands
        run: |
          # Sample commands to test
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c 'CREATE TABLE test (id SERIAL PRIMARY KEY, name TEXT);'
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c "INSERT INTO test (name) VALUES ('sample data');"
          PGPASSWORD=${{ env.POSTGRES_PASSWORD }} psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c 'SELECT * FROM test;'
      
    
  build:
    runs-on: ubuntu-latest
    needs: test  # Runs only if tests are successful

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}  # Docker Hub username stored as a secret in GitHub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret in GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Context to your Dockerfile location
        push: true  # Push the image after building
        tags: roshan450/docker_repo_13oct:latest
